# ---MLP Continuous PPO Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [64, 64]
    use_layer_norm: True
    activation: tanh
  action_head:
    _target_: stoix.networks.heads.NormalAffineTanhDistributionHeadPPO

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [64, 64]
    use_layer_norm: False
    activation: tanh
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
