# ---Environment Configs---
env_name: custom # Used for logging purposes and selection of the corresponding wrapper.

scenario:
  name: CartPolePerformance
  task_name: CartPolePerformance # For logging purposes.

kwargs:
  focus: 1.7

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# optional - defines the threshold that needs to be reached in order to consider the environment solved.
# if present then solve rate will be logged.
#solved_return_threshold: 500
